name: ci

on:
  pull_request:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

permissions: {}

jobs:
  cargo:
    uses: vexxhost/github-actions/.github/workflows/cargo.yml@main

  build:
    runs-on: ubuntu-24.04${{ matrix.target == 'aarch64' && '-arm' || '' }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        target: [x86_64, aarch64]
    steps:
      - uses: actions/checkout@v4
      - uses: rui314/setup-mold@v1
      - uses: Swatinem/rust-cache@v2
      - run: rustup show
      - uses: PyO3/maturin-action@v1
        with:
          command: build
          manylinux: '2_28'
          args: --release --sdist
          target: ${{ matrix.target }}
      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.target }}
          path: target/wheels/*.whl
          if-no-files-found: error

  coinstall:
    runs-on: depot-ubuntu-22.04
    timeout-minutes: 5
    needs: build
    strategy:
      fail-fast: false
      matrix:
        openstack-version: ["zed", "2023.1", "2023.2", "2024.1", "2024.2", "2025.1", "master"]
    steps:
      - uses: astral-sh/setup-uv@v5
        with:
            ignore-empty-workdir: true
      - uses: actions/download-artifact@v4
        with:
          name: wheel-x86_64
      - run: |
          uv venv
          uv pip install --constraint https://releases.openstack.org/constraints/upper/${{ matrix.openstack-version }} ./*.whl

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.VEXXHOST_BOT_PAT }}
      - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      - uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        if: github.event_name == 'pull_request' && github.event.pull_request.user.id == '29139614' && always()
        with:
          commit_message: "chore: apply pre-commit hook updates"
          commit_author: "renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"

  chart-vendor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: vexxhost/chart-vendor@3c91cecf08feb55ab66586b91b1a116b6cf0dbd9 # main
        with:
          charts-root: magnum_cluster_api/charts
